import { ScatterPlot } from './ScatterPlot';
import { createSvgElement } from '@wounded-pixels/svg-bindings';
import { results } from './ScatterPlot.stories';

test('basic construction', () => {
  expect(results.basic.outerHTML).toMatchInlineSnapshot(`
    "<div style=\\"min-width: 200px; min-height: 200px; width: 300px; height: 300px; max-width: 400px; max-height: 400px; border: 1px solid black; resize: both; overflow: hidden;\\"><svg viewBox=\\"0
             0
             100
             200\\" preserveAspectRatio=\\"xMidYMid meet\\" style=\\"width: 100%; height: 100%; display: inline-block; overflow: hidden;\\"><svg viewBox=\\"
            0
            -200
            100 200\\" preserveAspectRatio=\\"xMidYMid meet\\" style=\\"width: 100%; height: 100%; display: inline-block; overflow: hidden;\\" x=\\"15\\" y=\\"30\\" width=\\"70\\" height=\\"140\\"><rect x=\\"0\\" y=\\"-200\\" width=\\"100\\" height=\\"200\\" fill=\\"none\\"></rect><line x1=\\"20\\" y1=\\"0\\" x2=\\"20\\" y2=\\"-200\\" stroke=\\"lightgrey\\" stroke-width=\\"0.5\\"></line><line x1=\\"40\\" y1=\\"0\\" x2=\\"40\\" y2=\\"-200\\" stroke=\\"lightgrey\\" stroke-width=\\"0.5\\"></line><line x1=\\"60\\" y1=\\"0\\" x2=\\"60\\" y2=\\"-200\\" stroke=\\"lightgrey\\" stroke-width=\\"0.5\\"></line><line x1=\\"80\\" y1=\\"0\\" x2=\\"80\\" y2=\\"-200\\" stroke=\\"lightgrey\\" stroke-width=\\"0.5\\"></line><line x1=\\"0\\" y1=\\"-40\\" x2=\\"100\\" y2=\\"-40\\" stroke=\\"lightgrey\\" stroke-width=\\"0.5\\"></line><line x1=\\"0\\" y1=\\"-80\\" x2=\\"100\\" y2=\\"-80\\" stroke=\\"lightgrey\\" stroke-width=\\"0.5\\"></line><line x1=\\"0\\" y1=\\"-120\\" x2=\\"100\\" y2=\\"-120\\" stroke=\\"lightgrey\\" stroke-width=\\"0.5\\"></line><line x1=\\"0\\" y1=\\"-160\\" x2=\\"100\\" y2=\\"-160\\" stroke=\\"lightgrey\\" stroke-width=\\"0.5\\"></line><line x1=\\"0\\" y1=\\"0\\" x2=\\"100\\" y2=\\"0\\" stroke=\\"grey\\" stroke-width=\\"3\\"></line><line x1=\\"0\\" y1=\\"0\\" x2=\\"0\\" y2=\\"-200\\" stroke=\\"grey\\" stroke-width=\\"3\\"></line><circle fill=\\"grey\\" opacity=\\"0.5\\" stroke=\\"grey\\" stroke-width=\\"1\\" cx=\\"65\\" cy=\\"-150\\" r=\\"4\\"></circle><circle fill=\\"grey\\" opacity=\\"0.5\\" stroke=\\"grey\\" stroke-width=\\"1\\" cx=\\"70\\" cy=\\"-155\\" r=\\"4\\"></circle><circle fill=\\"grey\\" opacity=\\"0.5\\" stroke=\\"grey\\" stroke-width=\\"1\\" cx=\\"75\\" cy=\\"-160\\" r=\\"4\\"></circle><circle fill=\\"grey\\" opacity=\\"0.5\\" stroke=\\"grey\\" stroke-width=\\"1\\" cx=\\"50\\" cy=\\"-100\\" r=\\"4\\"></circle><circle fill=\\"grey\\" opacity=\\"0.5\\" stroke=\\"grey\\" stroke-width=\\"1\\" cx=\\"55\\" cy=\\"-110\\" r=\\"4\\"></circle><circle fill=\\"grey\\" opacity=\\"0.5\\" stroke=\\"grey\\" stroke-width=\\"1\\" cx=\\"60\\" cy=\\"-115\\" r=\\"4\\"></circle><circle fill=\\"grey\\" opacity=\\"0.5\\" stroke=\\"grey\\" stroke-width=\\"1\\" cx=\\"65\\" cy=\\"-120\\" r=\\"4\\"></circle></svg></svg></div>"
  `);
});

test('zoomed', () => {
  expect(results.zoomed.outerHTML).toMatchInlineSnapshot(`
    "<div style=\\"min-width: 200px; min-height: 200px; width: 300px; height: 300px; max-width: 400px; max-height: 400px; border: 1px solid black; resize: both; overflow: hidden;\\"><svg viewBox=\\"0
             0
             100
             100\\" preserveAspectRatio=\\"xMidYMid meet\\" style=\\"width: 100%; height: 100%; display: inline-block; overflow: hidden;\\"><svg viewBox=\\"
            45
            -160
            45 45\\" preserveAspectRatio=\\"xMidYMid meet\\" style=\\"width: 100%; height: 100%; display: inline-block; overflow: hidden;\\" x=\\"15\\" y=\\"15\\" width=\\"70\\" height=\\"70\\"><rect x=\\"0\\" y=\\"-160\\" width=\\"45\\" height=\\"45\\" fill=\\"none\\"></rect><line x1=\\"50\\" y1=\\"-115\\" x2=\\"50\\" y2=\\"-160\\" stroke=\\"lightgrey\\" stroke-width=\\"0.5\\"></line><line x1=\\"60\\" y1=\\"-115\\" x2=\\"60\\" y2=\\"-160\\" stroke=\\"lightgrey\\" stroke-width=\\"0.5\\"></line><line x1=\\"70\\" y1=\\"-115\\" x2=\\"70\\" y2=\\"-160\\" stroke=\\"lightgrey\\" stroke-width=\\"0.5\\"></line><line x1=\\"80\\" y1=\\"-115\\" x2=\\"80\\" y2=\\"-160\\" stroke=\\"lightgrey\\" stroke-width=\\"0.5\\"></line><line x1=\\"45\\" y1=\\"-120\\" x2=\\"90\\" y2=\\"-120\\" stroke=\\"lightgrey\\" stroke-width=\\"0.5\\"></line><line x1=\\"45\\" y1=\\"-130\\" x2=\\"90\\" y2=\\"-130\\" stroke=\\"lightgrey\\" stroke-width=\\"0.5\\"></line><line x1=\\"45\\" y1=\\"-140\\" x2=\\"90\\" y2=\\"-140\\" stroke=\\"lightgrey\\" stroke-width=\\"0.5\\"></line><line x1=\\"45\\" y1=\\"-150\\" x2=\\"90\\" y2=\\"-150\\" stroke=\\"lightgrey\\" stroke-width=\\"0.5\\"></line><line x1=\\"45\\" y1=\\"-115\\" x2=\\"90\\" y2=\\"-115\\" stroke=\\"grey\\" stroke-width=\\"0.5\\"></line><line x1=\\"45\\" y1=\\"-115\\" x2=\\"45\\" y2=\\"-160\\" stroke=\\"grey\\" stroke-width=\\"0.5\\"></line><circle fill=\\"blue\\" opacity=\\"0.5\\" stroke=\\"black\\" stroke-width=\\"0.5\\" cx=\\"65\\" cy=\\"-150\\" r=\\"1\\"></circle><circle fill=\\"blue\\" opacity=\\"0.5\\" stroke=\\"black\\" stroke-width=\\"0.5\\" cx=\\"70\\" cy=\\"-155\\" r=\\"1\\"></circle><circle fill=\\"blue\\" opacity=\\"0.5\\" stroke=\\"black\\" stroke-width=\\"0.5\\" cx=\\"75\\" cy=\\"-160\\" r=\\"1\\"></circle><circle fill=\\"orange\\" opacity=\\"0.5\\" stroke=\\"blue\\" stroke-width=\\"0.5\\" cx=\\"50\\" cy=\\"-100\\" r=\\"1.5\\"></circle><circle fill=\\"orange\\" opacity=\\"0.5\\" stroke=\\"blue\\" stroke-width=\\"0.5\\" cx=\\"55\\" cy=\\"-110\\" r=\\"1.5\\"></circle><circle fill=\\"orange\\" opacity=\\"0.5\\" stroke=\\"blue\\" stroke-width=\\"0.5\\" cx=\\"60\\" cy=\\"-115\\" r=\\"1.5\\"></circle><circle fill=\\"orange\\" opacity=\\"0.5\\" stroke=\\"blue\\" stroke-width=\\"0.5\\" cx=\\"65\\" cy=\\"-120\\" r=\\"1.5\\"></circle></svg></svg></div>"
  `);
});
